### PR TITLE
Use array of events for results functions

### LINKED ISSUE #29: Fix the results functions to take an array of events as input
Functions such as `numIncorrectCharacters` and `numMistakes` should take in an array of events as input. That way, calculations can be done on a range of events, which is useful for getting stats per second, or per word, for displaying for plots.

Alternatively, I could create a function that produces a tuple of stats that acts on one range of events. That way, I only have to loop through the events once to count the number of mistakes, remaining errors, WPM, Characters per minute, and so on.

### PR DESCRIPTION
**Pull request by NicksPatties**
Fixes #29

Instead of calculating results based on a series of values, wanted to accept an array of events. This will be useful for #24. I can calculate WPM of a slice of events, which means I can calculate WPM per second, which is necessary to create a plot.

### CODE REVIEW

File: cmd/root/results.go [hunk 1]
```diff
@@ -27,55 +27,81 @@ func requiredRunes(s string) []rune {
...
-	}
-	minLengthString := exercise
-	if len(typed) < len(exercise) {
-		minLengthString = typed
-	}
-	mins := end.Sub(start).Minutes()
-	incorrect := float64(numIncorrectCharacters(typed, exercise))
-	typedEntries := len(requiredRunes(minLengthString))
-	words := float64(typedEntries / wordSize)
+func wpm(events []event) float64 {
```
Comment (NicksPatties) [inline cmd/root/results.go:30]: I do want to make this one function that returns both the wpm and the raw wpm, since I'm doing a lot of the same stuff in both functions, but that can happen later.

File: cmd/root/sweet_test.go [hunk 2]
```diff
@@ -474,3 +475,33 @@ func TestFromArgsWithEmptyExerciseFiles(t *testing.T) {
...
+		input string
+		want  event
+	}
+
+	ts, _ := time.Parse("2006-01-02 15:04:05.000", "2024-10-07 13:46:47.679")
+	testCases := []testCase{
+		{
+			name:  "Easy case",
+			input: "2024-10-07 13:46:47.679: 0 a h",
+			want: event{
```
Comment (NicksPatties) [inline cmd/root/sweet_test.go:492]: Change this want to be a string, which I can use to parse the event in the function below. That way, I won't have to declare `ts` outside.
